# Enter your mnemonic here
MNEMONIC = "<YOUR MNEMONIC HERE>"

# Commut Hash
COMMIT_HASH = "<COMMIT HASH HERE>"

MAINNET_REST_URL = "rest+https://rest-kralum.neutron-1.neutron.org" 
MAINNET_CHAIN_ID = "neutron-1"

TESTNET_REST_URL = "rest+https://rest-palvus.pion-1.ntrn.tech"
TESTNET_CHAIN_ID = "pion-1"

ADDRESS_PREFIX = "neutron"
DENOM = "untrn"
GAS_PRICE = 0.01

# Contract Paths
ENTRY_POINT_CONTRACT_PATH = "../artifacts/skip_api_entry_point-aarch64.wasm"
SWAP_ADAPTER_PATH = "../artifacts/skip_api_swap_adapter_astroport-aarch64.wasm"
IBC_TRANSFER_ADAPTER_PATH = "../artifacts/skip_api_ibc_adapter_neutron_transfer-aarch64.wasm"

# SALT USED TO GENERATE A DETERMINSTIC ADDRESS
SALT = "1"

# @DEV MUST CHANGE SALT ACCORDINGLY TO OBTAIN THIS PRE GENERATED ADDRESS
ENTRY_POINT_PRE_GENERATED_ADDRESS = "<PRE GENERATED ADDRESS HERE>"

[[swap_venues]]
name = "neutron-astroport"
# Testnet name
#name = "testnet-neutron-astroport"

router_contract_address = "neutron1eeyntmsq448c68ez06jsy6h2mtjke5tpuplnwtjfwcdznqmw72kswnlmm0"
# Testnet address
#router_contract_address = "neutron12jm24l9lr9cupufqjuxpdjnnweana4h66tsx5cl800mke26td26sq7m05p"