# Enter your mnemonic here
MNEMONIC = "<YOUR MNEMONIC HERE>"

# Commut Hash
COMMIT_HASH = "80f8044b4400f727c9c765dc72c74ff88508eb68"

MAINNET_REST_URL = "rest+https://lcd.osmosis.zone/"
MAINNET_CHAIN_ID = "osmosis-1"

TESTNET_REST_URL = "rest+https://lcd.osmotest5.osmosis.zone/"
TESTNET_CHAIN_ID = "osmo-test-5" 

ADDRESS_PREFIX = "osmo"
DENOM = "uosmo"
GAS_PRICE = 0.01

# Contract Paths
ENTRY_POINT_CONTRACT_PATH = "../artifacts/skip_swap_entry_point-aarch64.wasm"
SWAP_ADAPTER_PATH = "../artifacts/skip_swap_osmosis_poolmanager_swap-aarch64.wasm"
IBC_TRANSFER_ADAPTER_PATH = "../artifacts/skip_swap_osmosis_ibc_transfer-aarch64.wasm"

# SALT USED TO GENERATE A DETERMINSTIC ADDRESS
SALT = "1"

# @DEV MUST CHANGE SALT ACCORDINGLY TO OBTAIN THIS PRE GENERATED ADDRESS
ENTRY_POINT_PRE_GENERATED_ADDRESS = "<PRE GENERATED ADDRESS HERE>"

# ADDRESS GRANTED PERMISSION BY GOVERNANCE TO UPLOAD CONTRACATS
PERMISSIONED_UPLOADER_ADDRESS = "osmo1raa4kyx5ypz75qqk3566c6slx2mw3qzsu6rymw"

[[swap_venues]]
name = "osmosis-poolmanager"